export type MatchaGrade = "ceremonial" | "premium" | "culinary" | "unknown";

export type FlavorScores = {
  umami: number;
  floral: number;
  nutty: number;
  bitter: number;
  sweet: number;
};

export type CafeReview = {
  id: string;
  author: string;
  text: string;
  rating?: number;
  date?: string;
};

export type Shop = {
  id: string;
  slug: string;
  name: string;
  area: string;
  /** Unset until someone rates it — a wishlisted place hasn't been tried yet. */
  rating?: number;
  reviewCount: number;
  signatureDrink: string;
  /** e.g. "Italian", "Mexican" -- distinct from signatureDrink, which is a
   * specific dish rather than a style of food. */
  cuisine?: string;
  /** A free-text note about why it's on the list, added at wishlist time --
   * distinct from the personal post-visit rating/comment in TriedNote. */
  notes?: string;
  priceTier: 1 | 2 | 3;
  location: {
    lat: number;
    lng: number;
    address: string;
  };
  matchaOrigin?: string;
  matchaGrade?: MatchaGrade;
  flavorTags?: string[];
  flavorScores?: FlavorScores;
  prepStyles?: string[];
  editorsPick?: boolean;
  rank?: number;
  coverImage?: string;
  photos?: string[];
  googleMapsUrl?: string;
  popularDishes?: string[];
  reviews?: CafeReview[];
};

/** A cafe as rendered by the app, tagged with whether it came from the
 * static seed data or was added locally by the user. */
export type MergedShop = Shop & { isCustom: boolean };

/** Fields the add/edit form collects. `id`/`slug` are generated by the
 * provider, not entered directly. */
export type NewCafeInput = Omit<Shop, "id" | "slug" | "reviewCount"> & {
  reviewCount?: number;
};
